---
title: "02_Add_Climate_Data"
output:
  html_document: default
editor_options:
  chunk_output_type: console
---

# Initialization

## 1. Setup layout parameters

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## 2. Setup global options

```{r Feux-agricoles-1, echo=FALSE}
# options(java.parameters = "- Xmx1024m") #Allow to increase memory limit
```

## 3. Load required packages

```{r Feux-agricoles-2, message=FALSE}
library(raster)
library(tidyverse) # Easily Install and Load the 'Tidyverse'
library(janitor) # Simple Tools for Examining and Cleaning Dirty Data
library(readxl) # Read Excel Files
library(lubridate) # Make Dealing with Dates a Little Easier
library(annotater) # Annotate Package Load Calls, [github::luisDVA/annotater] v0.1.3
library(sf) # Simple Features for R
library(tmap) # Thematic Maps
library(leaflet) # Create Interactive Web Maps with the JavaScript 'Leaflet'
library(tmaptools) # Thematic Map Tools
library(snakecase) # Convert Strings into any Case
library(ggridges) # Ridgeline Plots in 'ggplot2'
library(pilot) # A minimal ggplot2 theme with an accessible discrete color
library(ggdist) # Visualizations of Distributions and Uncertainty
library(inspectdf) # Inspection, Comparison and Visualisation of Data Frames
library(ggforce) # Accelerating 'ggplot2'
library(report) # Automated Reporting of Results and Statistical Models
library(mapview) # Interactive Viewing of Spatial Data in R
library(caret)
library(foreach)
library(doParallel)
```

## 4. Get data

```{r}
fire<-read_csv2("data/Working_files/Agricultural_Pastoral_Fire.csv")
fire_sf<-st_read("data/Working_files/Agricultural_Pastoral_Fire_sf.gpkg")
```

# Function created

```{r}
get.climate.at.location <- function(fire_location, climatic_variable) {
  # browser()
  fire_location %>%
    mutate(
      mois = as.character(mois),
      mois = if_else(str_length(mois) == 1, paste0("0", mois), mois),
      jour_nb = jour,
      jour = as.character(jour),
      jour = if_else(str_length(jour) == 1, paste0("0", jour), jour)
    ) -> fire_location
  climate_raster <-
    brick(
      paste0(
        "D:/Climate/ERA5-Land/data/",
        climatic_variable,
        "/",
        climatic_variable,
        "_",
        fire_location$annee,
        "_",
        fire_location$mois,
        "_MEAN.nc"
      )
    )
  # browser()
  data <- raster::extract(x = climate_raster[[as.numeric(fire_location$jour)]], st_as_sf(fire_location))
  return(data)
}
```

# Add Climate Data

```{r}
n.cores <- parallel::detectCores() - 1
# create the cluster
my.cluster <- parallel::makeCluster(n.cores,
  type = "PSOCK"
)

# register it to be used by %dopar%
doParallel::registerDoParallel(cl = my.cluster)

# check if it is registered (optional)
foreach::getDoParRegistered()
seq_variable <- list.files("D:/Climate/ERA5-Land/data/")[c(3, 5, 6)]

for (variable in seq_variable) {
  print(variable)
  print(now())
  climatic_variable <- variable
  data_vector <- foreach(
    i = 1:dim(fire_sf)[1], .packages = c("sf", "raster", "tidyverse"),
    .combine = "c"
  ) %dopar% {
    fire_sf %>%
      slice(i) -> fire_location
    print(i)
    get.climate.at.location(fire_location, climatic_variable)
  }
  fire_sf %>%
    mutate(var = data_vector) -> fire_sf
  colnames(fire_sf)[dim(fire_sf)[2]] <- paste0(climatic_variable)
}

parallel::stopCluster(cl = my.cluster)

fire_sf%>%
  mutate(temperature_C=`2m_temperature`-273.15,
         relative_humidity=`2m_relative_humidity`,
         wind_speed_ms=`10m_wind_speed`,
         .keep = "unused")->fire_sf

fire_sf%>%
  as_tibble()->fire

```

# Export data

```{r Feux-agricoles-14 ,echo=FALSE}
write_csv2(fire, "data/Working_files/Agricultural_Pastoral_Fire_02.csv")
st_write(fire_sf, "data/Working_files/Agricultural_Pastoral_Fire_sf_02.gpkg", append = FALSE)
write_csv2(fire, "data/Working_files/Agricultural_Pastoral_Fire.csv")
st_write(fire_sf, "data/Working_files/Agricultural_Pastoral_Fire_sf.gpkg", append = FALSE)
```
