---
title: "02_Data_prediction"
output:
  html_document: default
editor_options:
  chunk_output_type: console
---

# Initialization

## 1.  Setup layout parameters

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message = FALSE)
```

## 2.  Setup global options

```{r Feux-agricoles-1, echo=FALSE}
# options(java.parameters = "- Xmx1024m") #Allow to increase memory limit
```

## 3.  Load required packages

```{r Feux-agricoles-2, message=FALSE}
library(tidyverse) # Easily Install and Load the 'Tidyverse'
library(janitor) # Simple Tools for Examining and Cleaning Dirty Data
library(readxl) # Read Excel Files
library(lubridate) # Make Dealing with Dates a Little Easier
library(annotater) # Annotate Package Load Calls, [github::luisDVA/annotater] v0.1.3
library(sf) # Simple Features for R
library(tmap) # Thematic Maps
library(leaflet) # Create Interactive Web Maps with the JavaScript 'Leaflet'
library(tmaptools) # Thematic Map Tools
library(snakecase) # Convert Strings into any Case
library(ggridges) # Ridgeline Plots in 'ggplot2'
library(pilot) # A minimal ggplot2 theme with an accessible discrete color
library(ggdist) # Visualizations of Distributions and Uncertainty
library(inspectdf) # Inspection, Comparison and Visualisation of Data Frames
library(ggforce) # Accelerating 'ggplot2'
library(report) # Automated Reporting of Results and Statistical Models
library(mapview) # Interactive Viewing of Spatial Data in R
library(caret)
```

## 4.  Get data

```{r}
fire<-read_csv2("data/Agricultural_Pastoral_Fire.csv")
fire_sf<-st_read("data/Agricultural_Pastoral_Fire_sf.shp")
```

# Data prediction

```{r}
fire%>%
  filter(!is.na(surface_ha),
         !is.na(type_vegetation))%>%
  select(surface_ha,annee,mois,lat,lon)->fire_for_training

fire%>%
  filter(is.na(surface_ha),
         !is.na(type_vegetation))%>%
  select(surface_ha,annee,mois,lat,lon)->fire_for_prediction



model <- train(surface_ha ~ mois,
               data = fire_for_training,
               method = "lm")
fitControl <- trainControl(method = "repeatedcv",   
                           number = 10,     # number of folds
                           repeats = 10,
                           search = "random")    # repeated ten times

model.cv <- train(surface_ha ~ .,
               data = fire_for_training,
               method = "ridge",  # now we're using the lasso method
               trControl = fitControl,
               preProcess = c('scale', 'center'))  

model.cv   
pred<-predict(model.cv,fire_for_prediction)
```

#  Export data

```{r Feux-agricoles-14 ,echo=FALSE}
write_csv2(fire, "data/Working_files/Agricultural_Pastoral_Fire_04.csv")
st_write(fire_sf, "data/Working_files/Agricultural_Pastoral_Fire_sf_04.gpkg", append = FALSE)
write_csv2(fire, "data/Working_files/Agricultural_Pastoral_Fire.csv")
st_write(fire_sf, "data/Working_files/Agricultural_Pastoral_Fire_sf.gpkg", append = FALSE)
```
